module 3/04-MVC-Views-Part-2/lecture-final/dotnet/TechElevator.Web/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TechElevator.Web.DAL;

namespace TechElevator.Web.Controllers
{
    public class FilmsController : Controller
    {
        // films/index        
        public IActionResult Index()
        {
            IStarWarsDAL dal = new StarWarsDAL();
            var films = dal.GetFilms();

            return View(films);
        }

        //films/filmdetails/{id}
        //films/filmdetails?id={id}
        public IActionResult Detail(string id)
        {
            IStarWarsDAL dal = new StarWarsDAL();
            var film = dal.GetFilm(id);

            if (film == null)
            {
                return NotFound();
            }
            else
            {
                return View(film);
            }
        }
    }
}

module 3/04-MVC-Views-Part-2/lecture-final/dotnet/TechElevator.Web/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TechElevator.Web.DAL;
using TechElevator.Web.Models;

namespace TechElevator.Web.Controllers
{
    public class FoodController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreatureBreakfast(string creature)
        {
            // Received request from browers (Step 1 of MVC workflow)

            if (creature == null)
            {
                return NotFound();
            }

            IStarWarsDAL dal = new StarWarsDAL();
            EatDetailViewModel vm = new EatDetailViewModel();
            vm.Creature = creature;
            vm.Meal = "breakfast";

            // Get data from Model (Step 2 & 3 of MVC workflow)
            vm.FoodItems = dal.GetFoodInfo(vm.Creature, vm.Meal);

            // Send data to View (Step 4 & 5 of MVC workflow)
            var htmlResult = View("Eat", vm);

            // Send View data to browser (Step 6 of MVC workflow)
            return htmlResult;
        }


        [HttpGet]
        public IActionResult Eat(EatViewModel eatInfo)
        {
            if (eatInfo.Creature == null || eatInfo.Meal == null)
            {
                return NotFound();
            }

            // Received request from browers (Step 1 of MVC workflow)

            IStarWarsDAL dal = new StarWarsDAL();
            EatDetailViewModel vm = new EatDetailViewModel();
            vm.Creature = eatInfo.Creature;
            vm.Meal = eatInfo.Meal;

            // Get data from Model (Step 2 & 3 of MVC workflow)
            vm.FoodItems = dal.GetFoodInfo(eatInfo.Creature, eatInfo.Meal);

            // Send data to View (Step 4 & 5 of MVC workflow)
            var htmlResult = View(vm);

            // Send View data to browser (Step 6 of MVC workflow)
            return htmlResult;
        }

        //[HttpGet]
        //public IActionResult Eat(EatViewModel eatInfo)
        //{
        //    EatDetailViewModel vm = new EatDetailViewModel();
        //    vm.Creature = eatInfo.Creature;
        //    vm.Meal = eatInfo.Meal;

        //    List<string> test = new List<string>()
        //    {
        //        "banana",
        //        "salmon",
        //        "John"
        //    };
        //    vm.FoodItems = test;

        //    ViewData["EatInfo"] = vm;

        //    return View();
        //}
    }
}

module 3/04-MVC-Views-Part-2/lecture-final/dotnet/TechElevator.Web/Views/Films/Detail.cshtml
@model Film
@{
    ViewData["Title"] = Model.Name;
}

<h2>@Model.Name</h2>
<img src="@Model.ImageUrl" />

module 3/04-MVC-Views-Part-2/lecture-final/dotnet/TechElevator.Web/Views/Films/Index.cshtml
@model IList<Film>

@{
    ViewData["Title"] = "All Films";
}

<h2>All Films</h2>


<div id="movies">

    @foreach (var film in Model)
    {
        <div class="movie">
            <h3>@film.Name</h3>
            <p class="release-date">Released: @film.YearReleased</p>
            @if (String.IsNullOrEmpty(film.ImageUrl))
            {
                <a asp-controller="Films" asp-action="Detail" asp-route-id="@film.Id">
                    <img src="http://via.placeholder.com/768x400" />
                </a>
            }
            else
            {
                <a asp-controller="Films" asp-action="Detail" asp-route-id="@film.Id">
                    <img src="@film.ImageUrl" />
                </a>
            }
        </div>
    }
</div>

module 3/04-MVC-Views-Part-2/lecture-final/dotnet/TechElevator.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <ul>
            <li><a asp-controller="Films" asp-action="Index">All Films</a></li>
            <li><a asp-controller="Films" asp-action="Detail" asp-route-id="solo">Solo</a></li>
            <li><a asp-controller="Films" asp-action="Detail" asp-route-id="swviii">The Last Jedi</a></li>
            <li><a asp-controller="Films" asp-action="Detail" asp-route-id="rogue-one">Rogue One</a></li>
            <li><a asp-controller="Films" asp-action="Detail" asp-route-id="swix">Episode 9</a></li>
            <li><a asp-controller="Food" asp-action="Index">Munchies and Crunchies</a></li>
        </ul>
    </nav>
    @RenderBody()
</body>
</html>